self.instance.set_status.assert_called_once_with(200)
        self.instance.set_header.assert_any_call("Content-Type", "application/octet-stream")
        self.instance.set_header.assert_any_call("Access-Control-Expose-Headers", "Content-Disposition")
        self.instance.set_header.assert_any_call("Content-Disposition", "attachment; filename=file.txt")
        self.instance.set_header.assert_any_call("Content-Location", self.s3Loc)
        self.mock_reader_writer_instance.readByUri.assert_called_once_with(self.s3Loc)
        self.instance.write.assert_called_once_with(b"file content")
        self.instance.finish.assert_called_once()